services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres
    image: pgvector/pgvector:pg16
    ports:
        - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
